### ISSUE TITLE
Document History Tracking Wishlist

### ISSUE THREAD

**Issue by James1x0** [associatedemployers/trust-api#2]
Please see https://github.com/associatedemployers/trust-api/blob/master/lib/ticker/README.md for planned features.
#### Working List:
- [x] **Change History**
  - [x] Queryable
  - [x] Saved to resource
- [ ] **Audits**
  - [x] Stores user that changed document
  - [x] Stores time of change
- [x] **Readable Change Descriptor**
  _ex. Properties Changed/Deleted/Added by user {ObjectId}_
- [ ] **Rollbacks**
  - [x] Stores both updated and old document for rollbacks and auditing
  - [x] Rollback api
  - [x] Rollback event flag
  - [x] Flag superseded events 
- [x] **Detailed Change Log**
  - [x] Change type
  - [x] Left/Right side values via deep-diff module
  - [x] Path
- [x] **Backdating**
- [ ] **Per Change**
  - [ ] Notes!
  - [x] Flags! ( Like `Mistake` and `Superseded By Rollback` )
- [ ] **Systematic Calculations (BL)**
  - [ ] Effective Date
  - **FUTURE:**
    - [ ] Adjustment Calculation
- [ ] **Reversible to HistoryIndividual**
